name: Magiqol Sky Fabric Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Java config (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Determine mod version (tag)
        id: set_vars
        run: |
          MOD_VERSION=$(grep 'mod_version=' gradle.properties | sed -E 's/mod_version=(.*)/\1/' | tr -d '\n')
          
          if [ -z "$MOD_VERSION" ]; then
            echo "Error : Mod version (mod_version) cannot be read from gradle.properties."
            exit 1
          fi
          
          TAG_NAME="v$MOD_VERSION"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          
          echo "Readed version : $MOD_VERSION"
          
          JAR_BASE_NAME=$(grep 'archives_base_name=' gradle.properties | sed -E 's/archives_base_name=(.*)/\1/' | tr -d '\n')
          
          JAR_PATH=$(find build/libs/ -name "$JAR_BASE_NAME-$MOD_VERSION*.jar" | head -n 1)

          if [ -z "$JAR_PATH" ]; then
            echo "Error : JAR file not found (search of $JAR_BASE_NAME-$MOD_VERSION*.jar in build/libs/)."
            exit 1
          fi

          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT
          echo "JAR file found : $JAR_PATH"

      - name: Create and push tag
        run: |
          TAG=${{ steps.set_vars.outputs.tag }}
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_vars.outputs.tag }}
          name: Release ${{ steps.set_vars.outputs.tag }}
          body: |
            ## Nouveauté
            
            - Détails de la version ici.
          draft: false
          prerelease: false
          files: ${{ steps.set_vars.outputs.jar_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
